import type { RefObject } from 'react'
import type { EditorHandle } from '../types'
import { useInstrumentPreview } from './useInstrumentPreview'
import { useJianpuWorkerAudioActions } from './useJianpuWorkerAudioActions'
import { useJianpuWorkerExports } from './useJianpuWorkerExports'
import { useJianpuWorkerFormat } from './useJianpuWorkerFormat'
import { useJianpuWorkerImport } from './useJianpuWorkerImport'
import { useJianpuWorkerLifecycle } from './useJianpuWorkerLifecycle'
import { useJianpuWorkerPartDeclaration } from './useJianpuWorkerPartDeclaration'
import { useJianpuWorkerRenderRequests } from './useJianpuWorkerRenderRequests'
import { useJianpuWorkerShiftOctave } from './useJianpuWorkerShiftOctave'
import { useJianpuWorkerState } from './useJianpuWorkerState'
import type { JianpuWorkerState } from './useJianpuWorkerTypes'
import { useMeasureAudioPlayback } from './useMeasureAudioPlayback'
import { useSequenceNavigation } from './useSequenceNavigation'
import { useUnzippedTextFormat } from './useUnzippedTextFormat'
import { useUnzippedTextSnapshot } from './useUnzippedTextSnapshot'

export type { JianpuWorkerState } from './useJianpuWorkerTypes'

export function useJianpuWorker(
  source: string,
  disabledParts: ReadonlySet<string>,
  disabledLyrics: ReadonlySet<string>,
  soloedParts: ReadonlySet<string>,
  activeFile: string,
  soundfontBytes: Uint8Array | null,
  fontBytes: { sc: Uint8Array; tc: Uint8Array; mono: Uint8Array } | null,
  unzippedView: boolean,
  editorRef: RefObject<EditorHandle | null>,
  debounceMs = 300,
): JianpuWorkerState {
  const {
    parts,
    setParts,
    partDeclarations,
    setPartDeclarations,
    partsLoading,
    setPartsLoading,
    documents,
    setDocuments,
    wavUrl,
    setWavUrl,
    noteTimings,
    setNoteTimings,
    audioAvailable,
    setAudioAvailable,
    pdfAvailable,
    setPdfAvailable,
    pdfExporting,
    setPdfExporting,
    splitPdfExporting,
    setSplitPdfExporting,
    midiAvailable,
    setMidiAvailable,
    midiExporting,
    setMidiExporting,
    splitMidiExporting,
    setSplitMidiExporting,
    splitWavExporting,
    setSplitWavExporting,
    diagnostics,
    setDiagnostics,
    diagnosticViewZones,
    setDiagnosticViewZones,
    rendering,
    setRendering,
    audioGenerating,
    setAudioGenerating,
    selectedMeasureRange,
    setSelectedMeasureRange,
    highlightedDocuments,
    setHighlightedDocuments,
    measureSpans,
    setMeasureSpans,
    noteSpans,
    setNoteSpans,
    unzippedText,
    setUnzippedText,
    partMeasureRanges,
    setPartMeasureRanges,
    lyricsVerseRanges,
    setLyricsVerseRanges,
    sectionRanges,
    setSectionRanges,
    sequenceEntries,
    setSequenceEntries,
    highlightRenderRequestIdRef,
    latestHighlightRenderIdRef,
    measureSpansRequestIdRef,
    latestMeasureSpansIdRef,
    measureSpansRef,
    noteSpansRequestIdRef,
    latestNoteSpansIdRef,
    partMeasureRangesRef,
    lyricsVerseRangesRef,
    workerRef,
    wavUrlRef,
    partsRequestIdRef,
    updatePartDeclarationRequestIdRef,
    latestUpdatePartDeclarationIdRef,
    pendingPartDeclarationUpdatesRef,
    formatScoreRequestIdRef,
    latestFormatScoreIdRef,
    pendingFormatScoreRequestsRef,
    shiftPartOctaveTracker,
    importRequestIdRef,
    pendingImportsRef,
    renderRequestIdRef,
    audioRequestIdRef,
    pdfRequestIdRef,
    splitPdfRequestIdRef,
    midiRequestIdRef,
    splitMidiRequestIdRef,
    splitWavRequestIdRef,
    latestPartsIdRef,
    latestRenderIdRef,
    latestAudioIdRef,
    latestPdfIdRef,
    latestSplitPdfIdRef,
    latestMidiIdRef,
    latestSplitMidiIdRef,
    latestSplitWavIdRef,
    sourceRef,
    activeFileRef,
    enabledTracksRef,
    enabledPartNamesRef,
    disabledLyricsRef,
    audioAvailableRef,
    cursorOffsetTimerRef,
    lastSelectionRef,
    enabledTracks,
    disabledLyricsTracks,
    wavFilename,
  } = useJianpuWorkerState(
    source,
    activeFile,
    disabledParts,
    disabledLyrics,
    soloedParts,
  )

  const sequenceNav = useSequenceNavigation(sequenceEntries)
  useUnzippedTextSnapshot(unzippedView, sourceRef, setUnzippedText)

  const { setNextWavUrl, generateFullAudio } = useJianpuWorkerAudioActions({
    workerRef,
    sourceRef,
    enabledTracksRef,
    wavUrlRef,
    setWavUrl,
    audioGenerating,
    setAudioGenerating,
    audioRequestIdRef,
    latestAudioIdRef,
  })

  const {
    measureAudioGenerating,
    setMeasureAudioGenerating,
    measureAudioPlaying,
    measureAudioNoteTimings,
    measureAudioElement,
    setNextMeasureWavUrl,
    stopMeasurePlayback,
    playSelectedMeasures,
    playFromCurrentMeasure,
    playNoteSelection,
    latestMeasureAudioIdRef,
    measureWavUrlRef,
  } = useMeasureAudioPlayback({
    workerRef,
    sourceRef,
    enabledTracksRef,
    selectedMeasureRange,
    selectedSequenceRangeRef: sequenceNav.selectedSequenceRangeRef,
  })

  const {
    previewAudioPlaying,
    setPreviewAudioPlaying,
    previewInstrument,
    previewPercussion,
    stopPreviewInstrument,
    latestPreviewAudioIdRef,
    currentPreviewAudioRef,
  } = useInstrumentPreview({ workerRef })

  useJianpuWorkerLifecycle({
    workerRef,
    wavUrlRef,
    measureWavUrlRef,
    cursorOffsetTimerRef,
    soundfontBytes,
    fontBytes,
    audioAvailableRef,
    setAudioAvailable,
    setPdfAvailable,
    setMidiAvailable,
    latestPartsIdRef,
    setPartsLoading,
    setParts,
    setPartDeclarations,
    latestUpdatePartDeclarationIdRef,
    pendingPartDeclarationUpdatesRef,
    latestFormatScoreIdRef,
    pendingFormatScoreRequestsRef,
    shiftPartOctaveTracker,
    latestPdfIdRef,
    setPdfExporting,
    activeFileRef,
    enabledPartNamesRef,
    setDiagnostics,
    latestSplitPdfIdRef,
    setSplitPdfExporting,
    latestMidiIdRef,
    setMidiExporting,
    latestSplitMidiIdRef,
    setSplitMidiExporting,
    latestSplitWavIdRef,
    setSplitWavExporting,
    latestRenderIdRef,
    setRendering,
    setDocuments,
    setDiagnosticViewZones,
    latestAudioIdRef,
    setAudioGenerating,
    setNextWavUrl,
    setNoteTimings,
    latestMeasureAudioIdRef,
    setMeasureAudioGenerating,
    setNextMeasureWavUrl,
    latestHighlightRenderIdRef,
    setHighlightedDocuments,
    latestMeasureSpansIdRef,
    setMeasureSpans,
    latestNoteSpansIdRef,
    setNoteSpans,
    setSectionRanges,
    setSequenceEntries,
    latestPreviewAudioIdRef,
    currentPreviewAudioRef,
    setPreviewAudioPlaying,
    pendingImportsRef,
  })

  const { notifySelection, notifyUnzippedSelection } =
    useJianpuWorkerRenderRequests({
      workerRef,
      sourceRef,
      source,
      activeFile,
      debounceMs,
      enabledTracks,
      disabledLyricsTracks,
      setDocuments,
      setNextWavUrl,
      setDiagnostics,
      setPartsLoading,
      partsRequestIdRef,
      latestPartsIdRef,
      setRendering,
      renderRequestIdRef,
      latestRenderIdRef,
      selectedMeasureRange,
      setSelectedMeasureRange,
      setHighlightedDocuments,
      highlightRenderRequestIdRef,
      latestHighlightRenderIdRef,
      measureSpans,
      measureSpansRef,
      measureSpansRequestIdRef,
      latestMeasureSpansIdRef,
      noteSpansRequestIdRef,
      latestNoteSpansIdRef,
      cursorOffsetTimerRef,
      lastSelectionRef,
      unzippedView,
      partMeasureRangesRef,
      setPartMeasureRanges,
      lyricsVerseRangesRef,
      setLyricsVerseRanges,
    })

  const {
    exportPdf,
    exportSplitPdf,
    exportMidi,
    exportSplitMidi,
    exportSplitWav,
  } = useJianpuWorkerExports({
    workerRef,
    sourceRef,
    activeFileRef,
    enabledTracksRef,
    disabledLyricsRef,
    pdfExporting,
    splitPdfExporting,
    midiExporting,
    splitMidiExporting,
    splitWavExporting,
    setPdfExporting,
    setSplitPdfExporting,
    setMidiExporting,
    setSplitMidiExporting,
    setSplitWavExporting,
    pdfRequestIdRef,
    latestPdfIdRef,
    splitPdfRequestIdRef,
    latestSplitPdfIdRef,
    midiRequestIdRef,
    latestMidiIdRef,
    splitMidiRequestIdRef,
    latestSplitMidiIdRef,
    splitWavRequestIdRef,
    latestSplitWavIdRef,
  })

  const { updatePartDeclaration } = useJianpuWorkerPartDeclaration({
    workerRef,
    sourceRef,
    updatePartDeclarationRequestIdRef,
    latestUpdatePartDeclarationIdRef,
    pendingPartDeclarationUpdatesRef,
  })

  const { formatScore } = useJianpuWorkerFormat({
    workerRef,
    formatScoreRequestIdRef,
    latestFormatScoreIdRef,
    pendingFormatScoreRequestsRef,
  })

  const { shiftPartOctave } = useJianpuWorkerShiftOctave({
    workerRef,
    sourceRef,
    shiftPartOctaveTracker,
  })

  const { importFromFile } = useJianpuWorkerImport({
    workerRef,
    importRequestIdRef,
    pendingImportsRef,
  })

  const formatUnzippedText = useUnzippedTextFormat({
    source,
    unzippedText,
    editorRef,
    setUnzippedText,
  })

  return {
    parts,
    partDeclarations,
    partsLoading,
    documents,
    wavUrl,
    wavFilename,
    noteTimings,
    audioAvailable,
    pdfAvailable,
    pdfExporting,
    splitPdfExporting,
    midiAvailable,
    midiExporting,
    splitMidiExporting,
    splitWavExporting,
    diagnostics,
    diagnosticViewZones,
    rendering,
    audioGenerating,
    exportPdf,
    exportSplitPdf,
    exportMidi,
    exportSplitMidi,
    exportSplitWav,
    generateFullAudio,
    selectedMeasureRange,
    measureAudioGenerating,
    measureAudioPlaying,
    measureAudioNoteTimings,
    measureAudioElement,
    notifySelection,
    notifyUnzippedSelection,
    unzippedText,
    partMeasureRanges,
    lyricsVerseRanges,
    playSelectedMeasures,
    playFromCurrentMeasure,
    playNoteSelection,
    stopMeasurePlayback,
    highlightedDocuments,
    measureSpans,
    noteSpans,
    sectionRanges,
    sequenceEntries,
    selectedSequenceRange: sequenceNav.selectedSequenceRange,
    sequenceJumpToolbarProps: sequenceNav.sequenceJumpToolbarProps,
    previewInstrument,
    previewPercussion,
    stopPreviewInstrument,
    previewAudioPlaying,
    updatePartDeclaration,
    formatScore,
    shiftPartOctave,
    formatUnzippedText,
    importFromFile,
  }
}
