/// One guitar chord shape from the vendored chords-db (`vendor/chords-db/`),
/// strings ordered low E to high E. `frets` are relative to `base_fret`:
/// `-1` = muted, `0` = open, `1` = the diagram's first fret row (which is
/// absolute fret `base_fret`).
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct GuitarVoicing {
    pub(crate) frets: [i8; 6],
    pub(crate) base_fret: u8,
    /// Relative fret rows held down by a barre.
    pub(crate) barres: &'static [u8],
}

pub(crate) struct GuitarVoicingEntry {
    root_pitch_class: u8,
    suffix: &'static str,
    voicing: GuitarVoicing,
}

// Generated by `build.rs` from `vendor/chords-db/guitar.json`: defines
// `GUITAR_VOICINGS`, the first chords-db position of every chord.
include!(concat!(env!("OUT_DIR"), "/guitar_voicings_generated.rs"));

/// `root_pitch_class` is 0 = C ... 11 = B; `suffix` is a chords-db suffix
/// (`"major"`, `"m7"`, `"/G"`, `"m/C"`, ...).
pub(crate) fn find_guitar_voicing(
    root_pitch_class: i8,
    suffix: &str,
) -> Option<&'static GuitarVoicing> {
    GUITAR_VOICINGS
        .iter()
        .find(|entry| {
            i8::try_from(entry.root_pitch_class) == Ok(root_pitch_class) && entry.suffix == suffix
        })
        .map(|entry| &entry.voicing)
}

/// chords-db's name for a slash chord's bass note, by pitch class.
pub(crate) fn chords_db_bass_name(pitch_class: i8) -> &'static str {
    match pitch_class {
        1 => "C#",
        2 => "D",
        3 => "D#",
        4 => "E",
        5 => "F",
        6 => "F#",
        7 => "G",
        8 => "G#",
        9 => "A",
        10 => "Bb",
        11 => "B",
        _ => "C",
    }
}
