//! Thin wrapper around the constants generated by `build.rs` from
//! `fonts/fonts.json` — that manifest, not this file, is the actual single
//! source of truth for which font file backs each `FontFamily` role
//! (`FontFamily::Serif`/`SansSerif`/`Monospace` — see `src/compositor/types.rs`)
//! and the family name each one is addressed by in SVG/PDF output. Every
//! other consumer — `font_metrics` (glyph-advance measurement),
//! `serializer::mod` (inline SVG `font-family`), `pdf` (PDF export's
//! `fontdb` setup), and `cli` (default PDF fonts) — references the constants
//! below instead of its own copy of a filename or family-name literal.
//!
//! To experiment with a different Chinese font for a role, edit
//! `fonts/fonts.json` (see its own comments) and drop the new font file into
//! `fonts/` — no Rust or web code needs to change.
//!
//! `SansSerif` and `Monospace` are addressed through `fontdb`'s generic
//! `sans-serif`/`monospace` aliases (`set_sans_serif_family`/
//! `set_monospace_family` in `src/pdf.rs`), so their `_FONT_NAME` constant is
//! just an alias string — but in practice it (like `_FONT_FAMILY_CSS`'s bare
//! name) still needs to equal the font file's own name-table family, or PDF
//! export silently drops that text's embedded font; see `fonts/fonts.json`'s
//! comment for why. `Serif` is addressed by its own literal family name
//! only (`fontdb` resolves a literal `font-family` by matching a loaded
//! font's own name-table family), so it has no `_FONT_NAME` constant.

include!(concat!(env!("OUT_DIR"), "/fonts_generated.rs"));
