//! Thin wrapper around the constants generated by `build.rs` from
//! `fonts/fonts.json` — that manifest, not this file, is the actual single
//! source of truth for which font file backs each `FontFamily` role
//! (`FontFamily::Serif`/`SansSerif`/`Monospace` — see `src/compositor/types.rs`)
//! and the family name each one is addressed by in SVG/PDF output. Every
//! other consumer — `font_metrics` (glyph-advance measurement),
//! `serializer::mod` (inline SVG `font-family`), `pdf` (PDF export's
//! `fontdb` setup), and `FontBytesByFamily::embedded` (the CLI's PDF fonts) — references the constants
//! below instead of its own copy of a filename or family-name literal.
//!
//! To experiment with a different Chinese font for a role, edit
//! `fonts/fonts.json` (see its own comments) and drop the new font file into
//! `fonts/` — no Rust or web code needs to change.
//!
//! `SansSerif` and `Monospace` are addressed through `fontdb`'s generic
//! `sans-serif`/`monospace` aliases (`set_sans_serif_family`/
//! `set_monospace_family` in `src/pdf.rs`), so their `_FONT_NAME` constant is
//! just an alias string — but in practice it (like `_FONT_FAMILY_CSS`'s bare
//! name) still needs to equal the font file's own name-table family, or PDF
//! export silently drops that text's embedded font; see `fonts/fonts.json`'s
//! comment for why. `Serif` is addressed by its own literal family name
//! only (`fontdb` resolves a literal `font-family` by matching a loaded
//! font's own name-table family), so it has no `_FONT_NAME` constant.

include!(concat!(env!("OUT_DIR"), "/fonts_generated.rs"));

/// One font file's raw bytes per `FontFamily` role, keyed by role rather
/// than by what text each role happens to render — which role measures or
/// renders which text is decided on the Rust side only (see
/// `font_metrics` and `serializer::text::font_family_css`). Used both for
/// PDF export (`pdf::write_pdf` loads all three into `fontdb`) and, on the
/// `wasm32` build, for layout glyph measurement (`set_layout_font_bytes`),
/// where the bytes arrive at runtime through the wasm component's
/// `font-bytes-by-family` WIT record.
pub struct FontBytesByFamily {
    /// Backs `FontFamily::Serif`.
    pub serif: Vec<u8>,
    /// Backs `FontFamily::SansSerif`.
    pub sans_serif: Vec<u8>,
    /// Backs `FontFamily::Monospace`.
    pub monospace: Vec<u8>,
}

#[cfg(not(target_arch = "wasm32"))]
impl FontBytesByFamily {
    /// The fonts embedded at compile time from `fonts/fonts.json`.
    pub fn embedded() -> Self {
        Self {
            serif: SERIF_FONT_BYTES.to_vec(),
            sans_serif: SANS_SERIF_FONT_BYTES.to_vec(),
            monospace: MONOSPACE_FONT_BYTES.to_vec(),
        }
    }
}
